export const NEW_TYPES_CARTRIDGE = 'CARTRIDGE/NEW_TYPES_CARTRIDGE'
export const ADD_NEW_CARTRIDGE = 'CARTRIDGE/ADD_NEW_CARTRIDGE'
export const SHOW_MODAL_ADD_CARTRIDGE = 'CARTRIDGE/SHOW_MODAL_ADD_CARTRIDGE'
export const ADD_BRANCH_CARTRIDGES = 'CARTRIDGE/ADD_BRANCH_CARTRIDGES';
export const ADD_FINISH_REQUEST = 'CARTRIDGE/ADD_FINISH_REQUEST';
export const REMOVE_CARTRIDGE = 'CARTRIDGE/REMOVE_CARTRIDGE'
export const REMOVE_ALL_CARTRIDGE = 'CARTRIDGE/REMOVE_ALL_CARTRIDGE';

export const CARTRIDGE_FILTER_BRANCH = 'CARTRIDGE/FILTER_BRANCH';
export const CARTRIDGE_FILTER_MODEL = 'CARTRIDGE/FILTER_MODEL';

export const FINISH_REQUEST = 'FINISH/FINISH_REQUEST';

export const ADD_DEVICES = 'DEVICE/ADD_NEW_DEVICES';
export const DEVICE_FILTER_BRANCH = 'DEVICE/FILTER_BRANCH'
export const DATA_EXPORT_ON_SU = 'DEVICE/DATA_EXPORT_ON_SU'
export const DATA_EXPORT_IN_REPAIR = 'DEVICE/DATA_EXPORT_IN_REPAIR'
export const DATA_IMPORT_OF_REPAIR = 'DEVICE/DATA_IMPORT_OF_REPAIR'
export const DATA_EXPORT_TO_SU = 'DEVICE/DATA_EXPORT_TO_SU'

